import random
from xworld_task import XWorldTask

"""
This file implements an xworld teaching task.
The task class contains several stage functions.

Each stage function must return three outputs:

next_stage  - the name of the next stage function
reward      - the reward of the current stage
sentence    - the sentence generated by the current stage

Finally, the function get_stage_names() return all the stage functions the
user wants to register.
"""

class XWorldNavTarget(XWorldTask):
    def __init__(self, env):
        super(XWorldNavTarget, self).__init__(env)

    def idle(self):
        goals = self._get_goals()
        agent, _, _ = self._get_agent()
        targets = [g for g in goals if self._reachable(agent.loc, g.loc)]
        if targets:
            sel_goal = random.choice(targets)
            self._record_target(sel_goal.loc);
            self._bind("S -> start")
            self._bind("G -> '" + sel_goal.name + "'")
            return ["simple_navigation_reward", 0.0, self._generate()]
        else:
            return ["idle", 0, ""]

    def get_stage_names(self):
        """
        return all the stage names; does not have to be in order
        """
        return ["idle", "simple_navigation_reward"]

    def _define_grammar(self):
        all_goal_names = self._get_all_goal_names_as_rhs()
        grammar_str = """
        S --> start | finish | timeup
        start -> I1 | I2 | I3 | I4 | I5 | I6
        finish -> 'Well' 'done' '!'
        timeup -> 'Time' 'up' '.'
        I1 -> A G 'please' '.'
        I2 -> 'Please' A G '.'
        I3 -> A G '.'
        I4 -> G 'is' 'your' D '.'
        I5 -> G 'is' 'the' D '.'
        I6 -> Y A G '?'
        A -> 'go' 'to' | 'navigate' 'to' | 'reach' | 'move' 'to'
        Y -> 'Could' 'you' 'please' | 'Can' 'you' | 'Will' 'you'
        D -> 'destination' | 'target' | 'goal'
        G --> %s
        """ % all_goal_names
        return grammar_str, "S"
