if (WITH_ATARI)
  message("Info: Atari is added.")

  add_definitions(-DPY_ATARI)
  include(atari)
  add_subdirectory(games/arcade)
  set(OBJECT_LIBS_LIST ${OBJECT_LIBS_LIST} $<TARGET_OBJECTS:arcade>)
  if(NOT OpenCV_DIR)
    add_dependencies(arcade opencv)
  endif()
else()
  message("Warning: Atari is not added.")
endif()
